name: Build and Publish Permadeler Application

on:
  push:
    paths-ignore:
      - "doc/**"
    branches:
      - "**"
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java SDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17

      - name: Build backend with Maven
        run: |
          mvn -U -B clean verify
      - name: 📂 Deploy latest repository
        if: startsWith(github.ref, 'refs/tags/v')
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_ADDRESS }}
          username: ${{ secrets.FTP_LOGIN }}
          password: ${{ secrets.FTP_MDP }}
          port: 21
          protocol: ftp
          dangerous-clean-slate: true
          local-dir: ./releng/fr.adaussy.permadeler.product/target/repository/
          server-dir: www/permadeler/repository/latest/
      - name: 📂 Deploy latest product
        if: startsWith(github.ref, 'refs/tags/v')
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_ADDRESS }}
          username: ${{ secrets.FTP_LOGIN }}
          password: ${{ secrets.FTP_MDP }}
          port: 21
          protocol: ftp
          local-dir: ./releng/fr.adaussy.permadeler.product/target/products/
          server-dir: www/permadeler/product/latest/
          exclude: fr.adaussy.permadeler.product*/**
          dangerous-clean-slate: true
      - name: 📂 Deploy nightly repository
        if: startsWith(github.ref, 'refs/heads/master')
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_ADDRESS }}
          username: ${{ secrets.FTP_LOGIN }}
          password: ${{ secrets.FTP_MDP }}
          port: 21
          protocol: ftp
          local-dir: ./releng/fr.adaussy.permadeler.product/target/repository/
          server-dir: www/permadeler/repository/nightly/
          dangerous-clean-slate: true

    
